development:
  api_key: 137eac155623c0ee4f178396dadb9bee
  secret_key: 44d6f52858441be175d76ffaebaf3c83
  canvas_page_name: mysocialdog
  callback_url: http://localhost:3000/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 8888
    local_port: 3000
    server_alive_interval: 0
     
test:
  api_key: 137eac155623c0ee4f178396dadb9bee
  secret_key: 44d6f52858441be175d76ffaebaf3c83
  canvas_page_name: mysocialdog
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
    
production:
  api_key: 137eac155623c0ee4f178396dadb9bee
  secret_key: 44d6f52858441be175d76ffaebaf3c83
  canvas_page_name: mysocialdog
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0